-- Dev catalog: about 200 ingredients plus a few recipes and pantry items to browse.
-- Safe to re-run: it clears seed data first. Tests use test_seed.sql instead.
--
-- fdc_id and gram weights come from USDA FoodData Central, SR Legacy (April 2018),
-- which is public domain. Gram weights use USDA's portion for each unit, preferring
-- the medium size. The ml row is derived from a volume portion so every volume unit
-- can bridge to grams. Ingredients USDA does not cover have no fdc_id, and units
-- USDA has no portion for have no conversion row. Nothing here is estimated.

BEGIN;

TRUNCATE recipe_steps, recipe_ingredients, recipes, pantry_items,
         ingredient_unit_conversions, ingredient_aliases, ingredients, users
         CASCADE;

INSERT INTO users (email, display_name)
VALUES ('dev@stockpot.local', 'Dev User');

INSERT INTO ingredients (slug, canonical_name, category, default_unit, shelf_life_days, fdc_id) VALUES
  ('scallion',               'scallion',               'produce',   'each',   7,    170005),
  ('garlic',                 'garlic',                 'produce',   'clove',  60,   169230),
  ('yellow-onion',           'yellow onion',           'produce',   'each',   30,   170000),
  ('red-onion',              'red onion',              'produce',   'each',   30,   170000),
  ('shallot',                'shallot',                'produce',   'each',   30,   170499),
  ('leek',                   'leek',                   'produce',   'each',   14,   169246),
  ('carrot',                 'carrot',                 'produce',   'each',   21,   170393),
  ('celery',                 'celery',                 'produce',   'stalk',  14,   169988),
  ('ginger',                 'ginger',                 'produce',   'g',      21,   169231),
  ('bell-pepper',            'bell pepper',            'produce',   'each',   10,   170108),
  ('jalapeno',               'jalapeño',               'produce',   'each',   10,   168576),
  ('serrano-pepper',         'serrano pepper',         'produce',   'each',   10,   169395),
  ('russet-potato',          'russet potato',          'produce',   'each',   60,   170027),
  ('yukon-gold-potato',      'yukon gold potato',      'produce',   'each',   60,   170028),
  ('sweet-potato',           'sweet potato',           'produce',   'each',   30,   168482),
  ('tomato',                 'tomato',                 'produce',   'each',   7,    170457),
  ('cherry-tomato',          'cherry tomato',          'produce',   'cup',    7,    170457),
  ('cucumber',               'cucumber',               'produce',   'each',   7,    168409),
  ('zucchini',               'zucchini',               'produce',   'each',   7,    169291),
  ('butternut-squash',       'butternut squash',       'produce',   'each',   60,   169295),
  ('eggplant',               'eggplant',               'produce',   'each',   7,    169228),
  ('broccoli',               'broccoli',               'produce',   'head',   7,    170379),
  ('cauliflower',            'cauliflower',            'produce',   'head',   7,    169986),
  ('green-cabbage',          'green cabbage',          'produce',   'head',   30,   169975),
  ('napa-cabbage',           'napa cabbage',           'produce',   'head',   14,   169979),
  ('bok-choy',               'bok choy',               'produce',   'head',   5,    170390),
  ('spinach',                'spinach',                'produce',   'cup',    5,    168462),
  ('kale',                   'kale',                   'produce',   'bunch',  7,    168421),
  ('romaine-lettuce',        'romaine lettuce',        'produce',   'head',   7,    169247),
  ('arugula',                'arugula',                'produce',   'cup',    5,    169387),
  ('green-beans',            'green beans',            'produce',   'cup',    7,    169961),
  ('asparagus',              'asparagus',              'produce',   'bunch',  4,    168389),
  ('corn',                   'corn',                   'produce',   'each',   3,    169998),
  ('peas',                   'peas',                   'produce',   'cup',    3,    170419),
  ('cremini-mushroom',       'cremini mushroom',       'produce',   'cup',    7,    168434),
  ('shiitake-mushroom',      'shiitake mushroom',      'produce',   'cup',    7,    169242),
  ('avocado',                'avocado',                'produce',   'each',   5,    171706),
  ('lemon',                  'lemon',                  'produce',   'each',   21,   167746),
  ('lime',                   'lime',                   'produce',   'each',   21,   168155),
  ('orange',                 'orange',                 'produce',   'each',   21,   169917),
  ('apple',                  'apple',                  'produce',   'each',   30,   171688),
  ('banana',                 'banana',                 'produce',   'each',   5,    173944),
  ('strawberry',             'strawberry',             'produce',   'cup',    5,    167762),
  ('blueberry',              'blueberry',              'produce',   'cup',    7,    171711),
  ('radish',                 'radish',                 'produce',   'each',   14,   169276),
  ('beet',                   'beet',                   'produce',   'each',   30,   169145),
  ('fennel',                 'fennel',                 'produce',   'each',   7,    169385),
  ('basil',                  'basil',                  'herb',      'sprig',  5,    172232),
  ('cilantro',               'cilantro',               'herb',      'bunch',  7,    169997),
  ('flat-leaf-parsley',      'flat-leaf parsley',      'herb',      'bunch',  7,    170416),
  ('mint',                   'mint',                   'herb',      'sprig',  7,    173475),
  ('thyme',                  'thyme',                  'herb',      'sprig',  10,   173470),
  ('rosemary',               'rosemary',               'herb',      'sprig',  10,   173473),
  ('dill',                   'dill',                   'herb',      'sprig',  5,    172233),
  ('chives',                 'chives',                 'herb',      'tbsp',   5,    169994),
  ('sage',                   'sage',                   'herb',      'sprig',  7,    NULL),
  ('bay-leaf',               'bay leaf',               'herb',      'each',   730,  170917),
  ('oregano',                'oregano',                'herb',      'tsp',    730,  171328),
  ('kosher-salt',            'kosher salt',            'spice',     'tsp',    NULL, 173468),
  ('black-pepper',           'black pepper',           'spice',     'tsp',    730,  170931),
  ('white-pepper',           'white pepper',           'spice',     'tsp',    730,  170933),
  ('red-pepper-flakes',      'red pepper flakes',      'spice',     'tsp',    730,  170932),
  ('cayenne',                'cayenne',                'spice',     'tsp',    730,  170932),
  ('paprika',                'paprika',                'spice',     'tsp',    730,  171329),
  ('smoked-paprika',         'smoked paprika',         'spice',     'tsp',    730,  171329),
  ('chili-powder',           'chili powder',           'spice',     'tsp',    730,  171319),
  ('ground-cumin',           'ground cumin',           'spice',     'tsp',    730,  170923),
  ('ground-coriander',       'ground coriander',       'spice',     'tsp',    730,  170922),
  ('ground-turmeric',        'ground turmeric',        'spice',     'tsp',    730,  172231),
  ('ground-cinnamon',        'ground cinnamon',        'spice',     'tsp',    730,  171320),
  ('ground-nutmeg',          'ground nutmeg',          'spice',     'tsp',    730,  171326),
  ('ground-ginger',          'ground ginger',          'spice',     'tsp',    730,  170926),
  ('garlic-powder',          'garlic powder',          'spice',     'tsp',    730,  171325),
  ('onion-powder',           'onion powder',           'spice',     'tsp',    730,  171327),
  ('curry-powder',           'curry powder',           'spice',     'tsp',    730,  170924),
  ('garam-masala',           'garam masala',           'spice',     'tsp',    730,  NULL),
  ('five-spice-powder',      'five-spice powder',      'spice',     'tsp',    730,  NULL),
  ('star-anise',             'star anise',             'spice',     'each',   730,  NULL),
  ('whole-cloves',           'whole cloves',           'spice',     'each',   730,  171321),
  ('cardamom',               'cardamom',               'spice',     'tsp',    730,  170919),
  ('mustard-seed',           'mustard seed',           'spice',     'tsp',    730,  170929),
  ('fennel-seed',            'fennel seed',            'spice',     'tsp',    730,  171323),
  ('sesame-seeds',           'sesame seeds',           'nut_seed',  'tbsp',   365,  170150),
  ('vanilla-extract',        'vanilla extract',        'baking',    'tsp',    NULL, 173471),
  ('chuck-roast',            'chuck roast',            'protein',   'lb',     4,    169491),
  ('ground-beef',            'ground beef',            'protein',   'lb',     2,    174036),
  ('beef-short-ribs',        'beef short ribs',        'protein',   'lb',     4,    170827),
  ('flank-steak',            'flank steak',            'protein',   'lb',     4,    169433),
  ('chicken-thigh',          'chicken thigh',          'protein',   'lb',     2,    173627),
  ('chicken-breast',         'chicken breast',         'protein',   'lb',     2,    171077),
  ('whole-chicken',          'whole chicken',          'protein',   'each',   2,    171447),
  ('ground-pork',            'ground pork',            'protein',   'lb',     2,    167902),
  ('pork-shoulder',          'pork shoulder',          'protein',   'lb',     4,    167843),
  ('pork-chop',              'pork chop',              'protein',   'each',   4,    168238),
  ('bacon',                  'bacon',                  'protein',   'slice',  7,    168277),
  ('italian-sausage',        'italian sausage',        'protein',   'lb',     2,    171631),
  ('ground-turkey',          'ground turkey',          'protein',   'lb',     2,    171505),
  ('lamb-shoulder',          'lamb shoulder',          'protein',   'lb',     4,    172496),
  ('firm-tofu',              'firm tofu',              'protein',   'package',7,    172448),
  ('salmon-fillet',          'salmon fillet',          'seafood',   'lb',     2,    175167),
  ('cod-fillet',             'cod fillet',             'seafood',   'lb',     2,    171955),
  ('shrimp',                 'shrimp',                 'seafood',   'lb',     2,    175179),
  ('canned-tuna',            'canned tuna',            'seafood',   'can',    730,  173709),
  ('anchovy',                'anchovy',                'seafood',   'each',   365,  174183),
  ('mussels',                'mussels',                'seafood',   'lb',     2,    174216),
  ('large-egg',              'large egg',              'egg',       'each',   35,   171287),
  ('unsalted-butter',        'unsalted butter',        'dairy',     'g',      60,   173430),
  ('whole-milk',             'whole milk',             'dairy',     'cup',    7,    171265),
  ('heavy-cream',            'heavy cream',            'dairy',     'cup',    14,   170859),
  ('sour-cream',             'sour cream',             'dairy',     'cup',    21,   171257),
  ('buttermilk',             'buttermilk',             'dairy',     'cup',    14,   170874),
  ('plain-yogurt',           'plain yogurt',           'dairy',     'cup',    14,   171284),
  ('greek-yogurt',           'greek yogurt',           'dairy',     'cup',    14,   171304),
  ('cream-cheese',           'cream cheese',           'dairy',     'oz',     21,   173418),
  ('cheddar',                'cheddar',                'dairy',     'oz',     42,   173414),
  ('parmesan',               'parmesan',               'dairy',     'oz',     90,   170848),
  ('pecorino-romano',        'pecorino romano',        'dairy',     'oz',     90,   171249),
  ('mozzarella',             'mozzarella',             'dairy',     'oz',     14,   170845),
  ('feta',                   'feta',                   'dairy',     'oz',     30,   173420),
  ('gruyere',                'gruyère',                'dairy',     'oz',     42,   171242),
  ('ricotta',                'ricotta',                'dairy',     'cup',    7,    170851),
  ('all-purpose-flour',      'all-purpose flour',      'baking',    'cup',    240,  168894),
  ('bread-flour',            'bread flour',            'baking',    'cup',    240,  168896),
  ('whole-wheat-flour',      'whole wheat flour',      'baking',    'cup',    180,  168893),
  ('cornstarch',             'cornstarch',             'baking',    'tbsp',   NULL, 169698),
  ('granulated-sugar',       'granulated sugar',       'baking',    'cup',    NULL, 169655),
  ('brown-sugar',            'brown sugar',            'baking',    'cup',    NULL, 168833),
  ('powdered-sugar',         'powdered sugar',         'baking',    'cup',    NULL, 169656),
  ('honey',                  'honey',                  'baking',    'tbsp',   NULL, 169640),
  ('maple-syrup',            'maple syrup',            'baking',    'tbsp',   365,  169661),
  ('baking-soda',            'baking soda',            'baking',    'tsp',    540,  175040),
  ('baking-powder',          'baking powder',          'baking',    'tsp',    365,  172803),
  ('active-dry-yeast',       'active dry yeast',       'baking',    'package',365,  175043),
  ('cocoa-powder',           'cocoa powder',           'baking',    'tbsp',   730,  169593),
  ('dark-chocolate',         'dark chocolate',         'baking',    'oz',     365,  170273),
  ('panko',                  'panko',                  'baking',    'cup',    180,  174928),
  ('jasmine-rice',           'jasmine rice',           'grain',     'cup',    365,  168877),
  ('basmati-rice',           'basmati rice',           'grain',     'cup',    365,  168877),
  ('arborio-rice',           'arborio rice',           'grain',     'cup',    365,  168879),
  ('brown-rice',             'brown rice',             'grain',     'cup',    180,  169703),
  ('spaghetti',              'spaghetti',              'grain',     'oz',     730,  169736),
  ('penne',                  'penne',                  'grain',     'oz',     730,  169736),
  ('egg-noodles',            'egg noodles',            'grain',     'oz',     730,  169731),
  ('rice-noodles',           'rice noodles',           'grain',     'oz',     730,  169742),
  ('rolled-oats',            'rolled oats',            'grain',     'cup',    365,  173904),
  ('quinoa',                 'quinoa',                 'grain',     'cup',    730,  168874),
  ('couscous',               'couscous',               'grain',     'cup',    365,  169699),
  ('cornmeal',               'cornmeal',               'grain',     'cup',    365,  169697),
  ('bread',                  'bread',                  'grain',     'slice',  5,    174924),
  ('flour-tortilla',         'flour tortilla',         'grain',     'each',   14,   175037),
  ('corn-tortilla',          'corn tortilla',          'grain',     'each',   14,   175036),
  ('canned-chickpeas',       'canned chickpeas',       'legume',    'can',    730,  173801),
  ('canned-black-beans',     'canned black beans',     'legume',    'can',    730,  175238),
  ('canned-cannellini-beans','canned cannellini beans','legume',    'can',    730,  175204),
  ('canned-kidney-beans',    'canned kidney beans',    'legume',    'can',    730,  175195),
  ('brown-lentils',          'brown lentils',          'legume',    'cup',    365,  172420),
  ('red-lentils',            'red lentils',            'legume',    'cup',    365,  174284),
  ('edamame',                'edamame',                'legume',    'cup',    180,  168410),
  ('almonds',                'almonds',                'nut_seed',  'cup',    180,  170567),
  ('walnuts',                'walnuts',                'nut_seed',  'cup',    180,  170187),
  ('pecans',                 'pecans',                 'nut_seed',  'cup',    180,  170182),
  ('peanuts',                'peanuts',                'nut_seed',  'cup',    180,  172430),
  ('cashews',                'cashews',                'nut_seed',  'cup',    180,  170162),
  ('pine-nuts',              'pine nuts',              'nut_seed',  'tbsp',   90,   170591),
  ('peanut-butter',          'peanut butter',          'nut_seed',  'tbsp',   180,  172470),
  ('tahini',                 'tahini',                 'nut_seed',  'tbsp',   180,  170189),
  ('extra-virgin-olive-oil', 'extra-virgin olive oil', 'oil_fat',   'tbsp',   540,  171413),
  ('neutral-oil',            'neutral oil',            'oil_fat',   'tbsp',   365,  172336),
  ('sesame-oil',             'sesame oil',             'oil_fat',   'tsp',    365,  171016),
  ('coconut-oil',            'coconut oil',            'oil_fat',   'tbsp',   730,  171412),
  ('coconut-milk',           'coconut milk',           'oil_fat',   'can',    730,  170173),
  ('soy-sauce',              'soy sauce',              'condiment', 'tbsp',   730,  174277),
  ('fish-sauce',             'fish sauce',             'condiment', 'tbsp',   730,  174531),
  ('oyster-sauce',           'oyster sauce',           'condiment', 'tbsp',   365,  174529),
  ('hoisin-sauce',           'hoisin sauce',           'condiment', 'tbsp',   365,  172886),
  ('rice-vinegar',           'rice vinegar',           'condiment', 'tbsp',   730,  NULL),
  ('red-wine-vinegar',       'red wine vinegar',       'condiment', 'tbsp',   730,  172240),
  ('apple-cider-vinegar',    'apple cider vinegar',    'condiment', 'tbsp',   730,  173469),
  ('balsamic-vinegar',       'balsamic vinegar',       'condiment', 'tbsp',   730,  172241),
  ('white-vinegar',          'white vinegar',          'condiment', 'tbsp',   NULL, 172237),
  ('dijon-mustard',          'dijon mustard',          'condiment', 'tsp',    365,  NULL),
  ('mayonnaise',             'mayonnaise',             'condiment', 'tbsp',   60,   171009),
  ('ketchup',                'ketchup',                'condiment', 'tbsp',   180,  168556),
  ('worcestershire-sauce',   'worcestershire sauce',   'condiment', 'tsp',    730,  171610),
  ('sriracha',               'sriracha',               'condiment', 'tsp',    365,  171186),
  ('gochujang',              'gochujang',              'condiment', 'tbsp',   365,  NULL),
  ('white-miso',             'white miso',             'condiment', 'tbsp',   365,  172442),
  ('tomato-paste',           'tomato paste',           'condiment', 'tbsp',   730,  170459),
  ('canned-crushed-tomatoes','canned crushed tomatoes','condiment', 'can',    730,  170501),
  ('canned-whole-tomatoes',  'canned whole tomatoes',  'condiment', 'can',    730,  170051),
  ('chicken-stock',          'chicken stock',          'condiment', 'cup',    365,  172884),
  ('beef-stock',             'beef stock',             'condiment', 'cup',    365,  172883),
  ('vegetable-stock',        'vegetable stock',        'condiment', 'cup',    365,  171583),
  ('capers',                 'capers',                 'condiment', 'tbsp',   365,  172238),
  ('kalamata-olives',        'kalamata olives',        'condiment', 'cup',    365,  NULL),
  ('dry-red-wine',           'dry red wine',           'beverage',  'cup',    5,    173190),
  ('dry-white-wine',         'dry white wine',         'beverage',  'cup',    5,    174837),
  ('shaoxing-wine',          'shaoxing wine',          'beverage',  'tbsp',   365,  NULL),
  ('mirin',                  'mirin',                  'condiment', 'tbsp',   365,  NULL),
  ('lager',                  'lager',                  'beverage',  'fl_oz',  180,  168746);

-- Canonical names are added automatically by trigger. These are the extra aliases.
-- "pepper" and "coriander" map to two ingredients on purpose, so the resolver flags them.
INSERT INTO ingredient_aliases (alias, ingredient_id)
SELECT a.alias, i.id
FROM (VALUES
  ('green onion',             'scallion'),
  ('spring onion',            'scallion'),
  ('garlic clove',            'garlic'),
  ('onion',                   'yellow-onion'),
  ('brown onion',             'yellow-onion'),
  ('purple onion',            'red-onion'),
  ('shallots',                'shallot'),
  ('leeks',                   'leek'),
  ('carrots',                 'carrot'),
  ('celery stalk',            'celery'),
  ('celery rib',              'celery'),
  ('fresh ginger',            'ginger'),
  ('ginger root',             'ginger'),
  ('pepper',                  'bell-pepper'),
  ('capsicum',                'bell-pepper'),
  ('red bell pepper',         'bell-pepper'),
  ('sweet pepper',            'bell-pepper'),
  ('jalapeno',                'jalapeno'),
  ('jalapeno pepper',         'jalapeno'),
  ('serrano',                 'serrano-pepper'),
  ('potato',                  'russet-potato'),
  ('baking potato',           'russet-potato'),
  ('idaho potato',            'russet-potato'),
  ('yukon gold',              'yukon-gold-potato'),
  ('gold potato',             'yukon-gold-potato'),
  ('yam',                     'sweet-potato'),
  ('kumara',                  'sweet-potato'),
  ('tomatoes',                'tomato'),
  ('roma tomato',             'tomato'),
  ('cherry tomatoes',         'cherry-tomato'),
  ('grape tomato',            'cherry-tomato'),
  ('english cucumber',        'cucumber'),
  ('courgette',               'zucchini'),
  ('butternut',               'butternut-squash'),
  ('aubergine',               'eggplant'),
  ('broccoli florets',        'broccoli'),
  ('cauliflower florets',     'cauliflower'),
  ('cabbage',                 'green-cabbage'),
  ('chinese cabbage',         'napa-cabbage'),
  ('wombok',                  'napa-cabbage'),
  ('pak choi',                'bok-choy'),
  ('baby bok choy',           'bok-choy'),
  ('baby spinach',            'spinach'),
  ('lacinato kale',           'kale'),
  ('tuscan kale',             'kale'),
  ('cavolo nero',             'kale'),
  ('romaine',                 'romaine-lettuce'),
  ('lettuce',                 'romaine-lettuce'),
  ('cos lettuce',             'romaine-lettuce'),
  ('rocket',                  'arugula'),
  ('string beans',            'green-beans'),
  ('haricots verts',          'green-beans'),
  ('asparagus spears',        'asparagus'),
  ('sweet corn',              'corn'),
  ('corn on the cob',         'corn'),
  ('green peas',              'peas'),
  ('garden peas',             'peas'),
  ('mushroom',                'cremini-mushroom'),
  ('mushrooms',               'cremini-mushroom'),
  ('baby bella',              'cremini-mushroom'),
  ('button mushroom',         'cremini-mushroom'),
  ('shiitake',                'shiitake-mushroom'),
  ('avocados',                'avocado'),
  ('hass avocado',            'avocado'),
  ('lemons',                  'lemon'),
  ('limes',                   'lime'),
  ('oranges',                 'orange'),
  ('navel orange',            'orange'),
  ('apples',                  'apple'),
  ('granny smith',            'apple'),
  ('bananas',                 'banana'),
  ('strawberries',            'strawberry'),
  ('blueberries',             'blueberry'),
  ('radishes',                'radish'),
  ('beets',                   'beet'),
  ('beetroot',                'beet'),
  ('fennel bulb',             'fennel'),
  ('fresh basil',             'basil'),
  ('sweet basil',             'basil'),
  ('coriander',               'cilantro'),
  ('coriander leaves',        'cilantro'),
  ('fresh coriander',         'cilantro'),
  ('chinese parsley',         'cilantro'),
  ('parsley',                 'flat-leaf-parsley'),
  ('italian parsley',         'flat-leaf-parsley'),
  ('fresh mint',              'mint'),
  ('spearmint',               'mint'),
  ('fresh thyme',             'thyme'),
  ('fresh rosemary',          'rosemary'),
  ('fresh dill',              'dill'),
  ('dill weed',               'dill'),
  ('chive',                   'chives'),
  ('fresh sage',              'sage'),
  ('bay leaves',              'bay-leaf'),
  ('bay',                     'bay-leaf'),
  ('dried oregano',           'oregano'),
  ('salt',                    'kosher-salt'),
  ('coarse salt',             'kosher-salt'),
  ('pepper',                  'black-pepper'),
  ('ground black pepper',     'black-pepper'),
  ('peppercorns',             'black-pepper'),
  ('ground white pepper',     'white-pepper'),
  ('chili flakes',            'red-pepper-flakes'),
  ('crushed red pepper',      'red-pepper-flakes'),
  ('cayenne pepper',          'cayenne'),
  ('sweet paprika',           'paprika'),
  ('pimenton',                'smoked-paprika'),
  ('chile powder',            'chili-powder'),
  ('cumin',                   'ground-cumin'),
  ('coriander',               'ground-coriander'),
  ('turmeric',                'ground-turmeric'),
  ('cinnamon',                'ground-cinnamon'),
  ('nutmeg',                  'ground-nutmeg'),
  ('dried ginger',            'ground-ginger'),
  ('granulated garlic',       'garlic-powder'),
  ('chinese five spice',      'five-spice-powder'),
  ('cardamom pods',           'cardamom'),
  ('mustard seeds',           'mustard-seed'),
  ('fennel seeds',            'fennel-seed'),
  ('sesame seed',             'sesame-seeds'),
  ('toasted sesame seeds',    'sesame-seeds'),
  ('vanilla',                 'vanilla-extract'),
  ('beef chuck',              'chuck-roast'),
  ('chuck',                   'chuck-roast'),
  ('beef mince',              'ground-beef'),
  ('minced beef',             'ground-beef'),
  ('hamburger',               'ground-beef'),
  ('short ribs',              'beef-short-ribs'),
  ('flank',                   'flank-steak'),
  ('chicken thighs',          'chicken-thigh'),
  ('boneless chicken thigh',  'chicken-thigh'),
  ('chicken breasts',         'chicken-breast'),
  ('boneless chicken breast', 'chicken-breast'),
  ('chicken',                 'whole-chicken'),
  ('roasting chicken',        'whole-chicken'),
  ('pork mince',              'ground-pork'),
  ('minced pork',             'ground-pork'),
  ('pork butt',               'pork-shoulder'),
  ('boston butt',             'pork-shoulder'),
  ('pork chops',              'pork-chop'),
  ('streaky bacon',           'bacon'),
  ('sausage',                 'italian-sausage'),
  ('turkey mince',            'ground-turkey'),
  ('lamb',                    'lamb-shoulder'),
  ('tofu',                    'firm-tofu'),
  ('bean curd',               'firm-tofu'),
  ('salmon',                  'salmon-fillet'),
  ('cod',                     'cod-fillet'),
  ('white fish',              'cod-fillet'),
  ('prawns',                  'shrimp'),
  ('prawn',                   'shrimp'),
  ('tuna',                    'canned-tuna'),
  ('anchovies',               'anchovy'),
  ('anchovy fillets',         'anchovy'),
  ('mussel',                  'mussels'),
  ('egg',                     'large-egg'),
  ('eggs',                    'large-egg'),
  ('butter',                  'unsalted-butter'),
  ('milk',                    'whole-milk'),
  ('double cream',            'heavy-cream'),
  ('heavy whipping cream',    'heavy-cream'),
  ('cream',                   'heavy-cream'),
  ('yogurt',                  'plain-yogurt'),
  ('yoghurt',                 'plain-yogurt'),
  ('strained yogurt',         'greek-yogurt'),
  ('cheddar cheese',          'cheddar'),
  ('sharp cheddar',           'cheddar'),
  ('parmigiano reggiano',     'parmesan'),
  ('parmigiano',              'parmesan'),
  ('parmesan cheese',         'parmesan'),
  ('pecorino',                'pecorino-romano'),
  ('romano',                  'pecorino-romano'),
  ('fresh mozzarella',        'mozzarella'),
  ('mozzarella cheese',       'mozzarella'),
  ('feta cheese',             'feta'),
  ('gruyere',                 'gruyere'),
  ('gruyere cheese',          'gruyere'),
  ('ricotta cheese',          'ricotta'),
  ('flour',                   'all-purpose-flour'),
  ('ap flour',                'all-purpose-flour'),
  ('plain flour',             'all-purpose-flour'),
  ('strong flour',            'bread-flour'),
  ('wholemeal flour',         'whole-wheat-flour'),
  ('cornflour',               'cornstarch'),
  ('corn starch',             'cornstarch'),
  ('sugar',                   'granulated-sugar'),
  ('white sugar',             'granulated-sugar'),
  ('caster sugar',            'granulated-sugar'),
  ('light brown sugar',       'brown-sugar'),
  ('dark brown sugar',        'brown-sugar'),
  ('icing sugar',             'powdered-sugar'),
  ('confectioners sugar',     'powdered-sugar'),
  ('bicarbonate of soda',     'baking-soda'),
  ('bicarb',                  'baking-soda'),
  ('yeast',                   'active-dry-yeast'),
  ('dry yeast',               'active-dry-yeast'),
  ('unsweetened cocoa',       'cocoa-powder'),
  ('bittersweet chocolate',   'dark-chocolate'),
  ('semisweet chocolate',     'dark-chocolate'),
  ('chocolate chips',         'dark-chocolate'),
  ('panko breadcrumbs',       'panko'),
  ('breadcrumbs',             'panko'),
  ('rice',                    'jasmine-rice'),
  ('risotto rice',            'arborio-rice'),
  ('pasta',                   'spaghetti'),
  ('dried pasta',             'spaghetti'),
  ('short pasta',             'penne'),
  ('rice vermicelli',         'rice-noodles'),
  ('rice sticks',             'rice-noodles'),
  ('oats',                    'rolled-oats'),
  ('oatmeal',                 'rolled-oats'),
  ('old-fashioned oats',      'rolled-oats'),
  ('polenta',                 'cornmeal'),
  ('sandwich bread',          'bread'),
  ('white bread',             'bread'),
  ('tortilla',                'flour-tortilla'),
  ('tortillas',               'flour-tortilla'),
  ('corn tortillas',          'corn-tortilla'),
  ('chickpeas',               'canned-chickpeas'),
  ('garbanzo beans',          'canned-chickpeas'),
  ('black beans',             'canned-black-beans'),
  ('cannellini beans',        'canned-cannellini-beans'),
  ('white beans',             'canned-cannellini-beans'),
  ('white kidney beans',      'canned-cannellini-beans'),
  ('kidney beans',            'canned-kidney-beans'),
  ('red kidney beans',        'canned-kidney-beans'),
  ('lentils',                 'brown-lentils'),
  ('green lentils',           'brown-lentils'),
  ('masoor dal',              'red-lentils'),
  ('split red lentils',       'red-lentils'),
  ('soybeans',                'edamame'),
  ('almond',                  'almonds'),
  ('walnut',                  'walnuts'),
  ('pecan',                   'pecans'),
  ('peanut',                  'peanuts'),
  ('cashew',                  'cashews'),
  ('pignoli',                 'pine-nuts'),
  ('sesame paste',            'tahini'),
  ('olive oil',               'extra-virgin-olive-oil'),
  ('evoo',                    'extra-virgin-olive-oil'),
  ('vegetable oil',           'neutral-oil'),
  ('canola oil',              'neutral-oil'),
  ('cooking oil',             'neutral-oil'),
  ('toasted sesame oil',      'sesame-oil'),
  ('canned coconut milk',     'coconut-milk'),
  ('shoyu',                   'soy-sauce'),
  ('light soy sauce',         'soy-sauce'),
  ('nam pla',                 'fish-sauce'),
  ('nuoc mam',                'fish-sauce'),
  ('hoisin',                  'hoisin-sauce'),
  ('rice wine vinegar',       'rice-vinegar'),
  ('cider vinegar',           'apple-cider-vinegar'),
  ('balsamic',                'balsamic-vinegar'),
  ('distilled vinegar',       'white-vinegar'),
  ('vinegar',                 'white-vinegar'),
  ('dijon',                   'dijon-mustard'),
  ('mustard',                 'dijon-mustard'),
  ('mayo',                    'mayonnaise'),
  ('tomato ketchup',          'ketchup'),
  ('catsup',                  'ketchup'),
  ('worcestershire',          'worcestershire-sauce'),
  ('korean chili paste',      'gochujang'),
  ('miso',                    'white-miso'),
  ('shiro miso',              'white-miso'),
  ('tomato puree',            'tomato-paste'),
  ('crushed tomatoes',        'canned-crushed-tomatoes'),
  ('whole peeled tomatoes',   'canned-whole-tomatoes'),
  ('san marzano tomatoes',    'canned-whole-tomatoes'),
  ('tinned tomatoes',         'canned-whole-tomatoes'),
  ('chicken broth',           'chicken-stock'),
  ('beef broth',              'beef-stock'),
  ('vegetable broth',         'vegetable-stock'),
  ('caper',                   'capers'),
  ('olives',                  'kalamata-olives'),
  ('black olives',            'kalamata-olives'),
  ('red wine',                'dry-red-wine'),
  ('white wine',              'dry-white-wine'),
  ('chinese cooking wine',    'shaoxing-wine'),
  ('rice wine',               'shaoxing-wine'),
  ('sweet rice wine',         'mirin'),
  ('beer',                    'lager')
) AS a(alias, slug)
JOIN ingredients i ON i.slug = a.slug;

INSERT INTO ingredient_unit_conversions (ingredient_id, unit_code, grams)
SELECT i.id, c.unit_code, c.grams
FROM (VALUES
  ('scallion',               'cup',    100),
  ('scallion',               'tbsp',   6),
  ('scallion',               'each',   15),
  ('scallion',               'ml',     0.423),
  ('garlic',                 'cup',    136),
  ('garlic',                 'tsp',    2.8),
  ('garlic',                 'clove',  3),
  ('garlic',                 'ml',     0.575),
  ('yellow-onion',           'cup',    160),
  ('yellow-onion',           'tbsp',   10),
  ('yellow-onion',           'each',   110),
  ('yellow-onion',           'slice',  14),
  ('yellow-onion',           'ml',     0.676),
  ('red-onion',              'cup',    160),
  ('red-onion',              'tbsp',   10),
  ('red-onion',              'each',   110),
  ('red-onion',              'slice',  14),
  ('red-onion',              'ml',     0.676),
  ('shallot',                'tbsp',   10),
  ('shallot',                'ml',     0.676),
  ('leek',                   'cup',    89),
  ('leek',                   'each',   89),
  ('leek',                   'slice',  6),
  ('leek',                   'ml',     0.376),
  ('carrot',                 'cup',    128),
  ('carrot',                 'each',   61),
  ('carrot',                 'slice',  3),
  ('carrot',                 'ml',     0.541),
  ('celery',                 'cup',    101),
  ('celery',                 'tbsp',   7.5),
  ('celery',                 'stalk',  40),
  ('celery',                 'ml',     0.427),
  ('ginger',                 'tsp',    2),
  ('ginger',                 'cup',    96),
  ('ginger',                 'slice',  2.2),
  ('ginger',                 'ml',     0.406),
  ('bell-pepper',            'cup',    149),
  ('bell-pepper',            'tbsp',   9.3),
  ('bell-pepper',            'each',   119),
  ('bell-pepper',            'ml',     0.63),
  ('jalapeno',               'cup',    90),
  ('jalapeno',               'each',   14),
  ('jalapeno',               'ml',     0.38),
  ('serrano-pepper',         'cup',    105),
  ('serrano-pepper',         'each',   6.1),
  ('serrano-pepper',         'ml',     0.444),
  ('russet-potato',          'cup',    150),
  ('russet-potato',          'each',   213),
  ('russet-potato',          'ml',     0.634),
  ('yukon-gold-potato',      'cup',    150),
  ('yukon-gold-potato',      'each',   213),
  ('yukon-gold-potato',      'ml',     0.634),
  ('sweet-potato',           'cup',    133),
  ('sweet-potato',           'each',   130),
  ('sweet-potato',           'ml',     0.562),
  ('tomato',                 'cup',    149),
  ('tomato',                 'each',   123),
  ('tomato',                 'slice',  20),
  ('tomato',                 'ml',     0.63),
  ('cherry-tomato',          'cup',    149),
  ('cherry-tomato',          'each',   123),
  ('cherry-tomato',          'slice',  20),
  ('cherry-tomato',          'ml',     0.63),
  ('cucumber',               'cup',    104),
  ('cucumber',               'each',   301),
  ('cucumber',               'ml',     0.44),
  ('zucchini',               'cup',    124),
  ('zucchini',               'each',   196),
  ('zucchini',               'slice',  9.9),
  ('zucchini',               'ml',     0.524),
  ('butternut-squash',       'cup',    140),
  ('butternut-squash',       'ml',     0.592),
  ('eggplant',               'cup',    82),
  ('eggplant',               'each',   548),
  ('eggplant',               'ml',     0.347),
  ('broccoli',               'cup',    91),
  ('broccoli',               'bunch',  608),
  ('broccoli',               'stalk',  151),
  ('broccoli',               'ml',     0.385),
  ('cauliflower',            'cup',    107),
  ('cauliflower',            'head',   588),
  ('cauliflower',            'ml',     0.452),
  ('green-cabbage',          'cup',    89),
  ('green-cabbage',          'head',   908),
  ('green-cabbage',          'ml',     0.376),
  ('napa-cabbage',           'cup',    76),
  ('napa-cabbage',           'ml',     0.321),
  ('bok-choy',               'cup',    70),
  ('bok-choy',               'head',   840),
  ('bok-choy',               'ml',     0.296),
  ('spinach',                'cup',    30),
  ('spinach',                'bunch',  340),
  ('spinach',                'package',284),
  ('spinach',                'ml',     0.127),
  ('kale',                   'cup',    21),
  ('kale',                   'ml',     0.089),
  ('romaine-lettuce',        'cup',    47),
  ('romaine-lettuce',        'head',   626),
  ('romaine-lettuce',        'ml',     0.199),
  ('arugula',                'cup',    20),
  ('arugula',                'ml',     0.085),
  ('green-beans',            'cup',    100),
  ('green-beans',            'ml',     0.423),
  ('asparagus',              'cup',    134),
  ('asparagus',              'ml',     0.566),
  ('corn',                   'cup',    145),
  ('corn',                   'each',   102),
  ('corn',                   'ml',     0.613),
  ('peas',                   'cup',    145),
  ('peas',                   'ml',     0.613),
  ('cremini-mushroom',       'cup',    87),
  ('cremini-mushroom',       'ml',     0.368),
  ('avocado',                'cup',    230),
  ('avocado',                'each',   136),
  ('avocado',                'ml',     0.972),
  ('lemon',                  'cup',    212),
  ('lemon',                  'each',   58),
  ('lemon',                  'ml',     0.896),
  ('lime',                   'each',   67),
  ('orange',                 'cup',    165),
  ('orange',                 'each',   140),
  ('orange',                 'ml',     0.697),
  ('apple',                  'cup',    125),
  ('apple',                  'each',   182),
  ('apple',                  'ml',     0.528),
  ('banana',                 'cup',    225),
  ('banana',                 'each',   118),
  ('banana',                 'ml',     0.951),
  ('strawberry',             'cup',    152),
  ('strawberry',             'each',   12),
  ('strawberry',             'ml',     0.642),
  ('blueberry',              'cup',    148),
  ('blueberry',              'ml',     0.626),
  ('radish',                 'cup',    116),
  ('radish',                 'each',   4.5),
  ('radish',                 'slice',  1),
  ('radish',                 'ml',     0.49),
  ('beet',                   'cup',    136),
  ('beet',                   'each',   82),
  ('beet',                   'ml',     0.575),
  ('fennel',                 'cup',    87),
  ('fennel',                 'each',   234),
  ('fennel',                 'ml',     0.368),
  ('basil',                  'tbsp',   2.7),
  ('basil',                  'cup',    24),
  ('basil',                  'ml',     0.101),
  ('cilantro',               'cup',    16),
  ('cilantro',               'sprig',  2.2),
  ('cilantro',               'ml',     0.068),
  ('flat-leaf-parsley',      'cup',    60),
  ('flat-leaf-parsley',      'tbsp',   3.8),
  ('flat-leaf-parsley',      'sprig',  1),
  ('flat-leaf-parsley',      'ml',     0.254),
  ('mint',                   'tbsp',   5.7),
  ('mint',                   'ml',     0.385),
  ('thyme',                  'tsp',    0.8),
  ('thyme',                  'ml',     0.162),
  ('rosemary',               'tsp',    0.7),
  ('rosemary',               'tbsp',   1.7),
  ('rosemary',               'ml',     0.115),
  ('dill',                   'sprig',  0.2),
  ('dill',                   'cup',    8.9),
  ('dill',                   'ml',     0.038),
  ('chives',                 'tbsp',   3),
  ('chives',                 'tsp',    1),
  ('chives',                 'ml',     0.203),
  ('bay-leaf',               'tsp',    0.6),
  ('bay-leaf',               'tbsp',   1.8),
  ('bay-leaf',               'ml',     0.122),
  ('oregano',                'tsp',    1),
  ('oregano',                'ml',     0.203),
  ('kosher-salt',            'tsp',    6),
  ('kosher-salt',            'tbsp',   18),
  ('kosher-salt',            'cup',    292),
  ('kosher-salt',            'ml',     1.234),
  ('black-pepper',           'tsp',    2.3),
  ('black-pepper',           'tbsp',   6.9),
  ('black-pepper',           'ml',     0.467),
  ('white-pepper',           'tsp',    2.4),
  ('white-pepper',           'tbsp',   7.1),
  ('white-pepper',           'ml',     0.48),
  ('red-pepper-flakes',      'tsp',    1.8),
  ('red-pepper-flakes',      'tbsp',   5.3),
  ('red-pepper-flakes',      'ml',     0.358),
  ('cayenne',                'tsp',    1.8),
  ('cayenne',                'tbsp',   5.3),
  ('cayenne',                'ml',     0.358),
  ('paprika',                'tsp',    2.3),
  ('paprika',                'tbsp',   6.8),
  ('paprika',                'ml',     0.46),
  ('smoked-paprika',         'tsp',    2.3),
  ('smoked-paprika',         'tbsp',   6.8),
  ('smoked-paprika',         'ml',     0.46),
  ('chili-powder',           'tsp',    2.7),
  ('chili-powder',           'tbsp',   8),
  ('chili-powder',           'ml',     0.541),
  ('ground-cumin',           'tsp',    2.1),
  ('ground-cumin',           'tbsp',   6),
  ('ground-cumin',           'ml',     0.406),
  ('ground-coriander',       'tsp',    1.8),
  ('ground-coriander',       'tbsp',   5),
  ('ground-coriander',       'ml',     0.338),
  ('ground-turmeric',        'tsp',    3),
  ('ground-turmeric',        'tbsp',   9.4),
  ('ground-turmeric',        'ml',     0.636),
  ('ground-cinnamon',        'tsp',    2.6),
  ('ground-cinnamon',        'tbsp',   7.8),
  ('ground-cinnamon',        'ml',     0.527),
  ('ground-nutmeg',          'tsp',    2.2),
  ('ground-nutmeg',          'tbsp',   7),
  ('ground-nutmeg',          'ml',     0.473),
  ('ground-ginger',          'tsp',    1.8),
  ('ground-ginger',          'tbsp',   5.2),
  ('ground-ginger',          'ml',     0.352),
  ('garlic-powder',          'tsp',    3.1),
  ('garlic-powder',          'tbsp',   9.7),
  ('garlic-powder',          'ml',     0.656),
  ('onion-powder',           'tsp',    2.4),
  ('onion-powder',           'tbsp',   6.9),
  ('onion-powder',           'ml',     0.467),
  ('curry-powder',           'tsp',    2),
  ('curry-powder',           'tbsp',   6.3),
  ('curry-powder',           'ml',     0.426),
  ('whole-cloves',           'tsp',    2.1),
  ('whole-cloves',           'tbsp',   6.5),
  ('whole-cloves',           'ml',     0.44),
  ('cardamom',               'tsp',    2),
  ('cardamom',               'tbsp',   5.8),
  ('cardamom',               'ml',     0.392),
  ('mustard-seed',           'tsp',    2),
  ('mustard-seed',           'tbsp',   6.3),
  ('mustard-seed',           'ml',     0.426),
  ('fennel-seed',            'tsp',    2),
  ('fennel-seed',            'tbsp',   5.8),
  ('fennel-seed',            'ml',     0.392),
  ('sesame-seeds',           'cup',    144),
  ('sesame-seeds',           'tbsp',   9),
  ('sesame-seeds',           'ml',     0.609),
  ('vanilla-extract',        'tsp',    4.2),
  ('vanilla-extract',        'tbsp',   13),
  ('vanilla-extract',        'cup',    208),
  ('vanilla-extract',        'ml',     0.879),
  ('chicken-breast',         'package',926),
  ('pork-chop',              'each',   199),
  ('bacon',                  'slice',  28),
  ('bacon',                  'package',442),
  ('firm-tofu',              'cup',    252),
  ('firm-tofu',              'ml',     1.065),
  ('canned-tuna',            'can',    165),
  ('canned-tuna',            'cup',    154),
  ('canned-tuna',            'ml',     0.651),
  ('anchovy',                'each',   4),
  ('anchovy',                'can',    45),
  ('mussels',                'cup',    150),
  ('mussels',                'each',   16),
  ('mussels',                'ml',     0.634),
  ('large-egg',              'each',   50),
  ('large-egg',              'cup',    243),
  ('large-egg',              'ml',     1.027),
  ('unsalted-butter',        'tbsp',   14.2),
  ('unsalted-butter',        'cup',    227),
  ('unsalted-butter',        'ml',     0.959),
  ('whole-milk',             'cup',    244),
  ('whole-milk',             'fl_oz',  30.5),
  ('whole-milk',             'tbsp',   15),
  ('whole-milk',             'ml',     1.031),
  ('heavy-cream',            'cup',    120),
  ('heavy-cream',            'tbsp',   15),
  ('heavy-cream',            'fl_oz',  29.8),
  ('heavy-cream',            'ml',     0.507),
  ('sour-cream',             'tbsp',   12),
  ('sour-cream',             'cup',    230),
  ('sour-cream',             'ml',     0.972),
  ('buttermilk',             'cup',    245),
  ('buttermilk',             'fl_oz',  30.6),
  ('buttermilk',             'ml',     1.036),
  ('plain-yogurt',           'cup',    245),
  ('plain-yogurt',           'ml',     1.036),
  ('cream-cheese',           'tbsp',   14.5),
  ('cream-cheese',           'cup',    232),
  ('cream-cheese',           'package',85),
  ('cream-cheese',           'ml',     0.981),
  ('cheddar',                'cup',    132),
  ('cheddar',                'slice',  28),
  ('cheddar',                'ml',     0.558),
  ('parmesan',               'package',28.4),
  ('pecorino-romano',        'package',28.4),
  ('mozzarella',             'cup',    112),
  ('mozzarella',             'slice',  28.3),
  ('mozzarella',             'ml',     0.473),
  ('feta',                   'cup',    150),
  ('feta',                   'ml',     0.634),
  ('gruyere',                'slice',  28),
  ('gruyere',                'cup',    132),
  ('gruyere',                'package',170),
  ('gruyere',                'ml',     0.558),
  ('ricotta',                'cup',    248),
  ('ricotta',                'ml',     1.048),
  ('all-purpose-flour',      'cup',    125),
  ('all-purpose-flour',      'ml',     0.528),
  ('bread-flour',            'cup',    137),
  ('bread-flour',            'ml',     0.579),
  ('whole-wheat-flour',      'cup',    120),
  ('whole-wheat-flour',      'ml',     0.507),
  ('cornstarch',             'cup',    128),
  ('cornstarch',             'ml',     0.541),
  ('granulated-sugar',       'tsp',    4.2),
  ('granulated-sugar',       'cup',    200),
  ('granulated-sugar',       'ml',     0.845),
  ('brown-sugar',            'tsp',    3),
  ('brown-sugar',            'cup',    220),
  ('brown-sugar',            'ml',     0.93),
  ('powdered-sugar',         'cup',    120),
  ('powdered-sugar',         'tbsp',   8),
  ('powdered-sugar',         'tsp',    2.5),
  ('powdered-sugar',         'ml',     0.507),
  ('honey',                  'cup',    339),
  ('honey',                  'tbsp',   21),
  ('honey',                  'package',14),
  ('honey',                  'ml',     1.433),
  ('maple-syrup',            'tbsp',   20),
  ('maple-syrup',            'cup',    315),
  ('maple-syrup',            'ml',     1.331),
  ('baking-soda',            'tsp',    4.6),
  ('baking-soda',            'ml',     0.933),
  ('baking-powder',          'tsp',    4.6),
  ('baking-powder',          'ml',     0.933),
  ('active-dry-yeast',       'tsp',    4),
  ('active-dry-yeast',       'tbsp',   12),
  ('active-dry-yeast',       'package',7.2),
  ('active-dry-yeast',       'ml',     0.812),
  ('cocoa-powder',           'cup',    86),
  ('cocoa-powder',           'tbsp',   5.4),
  ('cocoa-powder',           'ml',     0.364),
  ('panko',                  'cup',    108),
  ('panko',                  'ml',     0.456),
  ('jasmine-rice',           'cup',    185),
  ('jasmine-rice',           'ml',     0.782),
  ('basmati-rice',           'cup',    185),
  ('basmati-rice',           'ml',     0.782),
  ('arborio-rice',           'cup',    195),
  ('arborio-rice',           'ml',     0.824),
  ('brown-rice',             'cup',    185),
  ('brown-rice',             'ml',     0.782),
  ('spaghetti',              'cup',    91),
  ('spaghetti',              'ml',     0.385),
  ('penne',                  'cup',    91),
  ('penne',                  'ml',     0.385),
  ('egg-noodles',            'cup',    38),
  ('egg-noodles',            'ml',     0.161),
  ('rolled-oats',            'cup',    81),
  ('rolled-oats',            'ml',     0.342),
  ('quinoa',                 'cup',    170),
  ('quinoa',                 'ml',     0.719),
  ('couscous',               'cup',    173),
  ('couscous',               'ml',     0.731),
  ('cornmeal',               'cup',    122),
  ('cornmeal',               'ml',     0.516),
  ('bread',                  'slice',  29),
  ('bread',                  'cup',    45),
  ('bread',                  'ml',     0.19),
  ('flour-tortilla',         'each',   30),
  ('flour-tortilla',         'package',407),
  ('corn-tortilla',          'each',   24),
  ('canned-chickpeas',       'can',    254),
  ('canned-chickpeas',       'cup',    152),
  ('canned-chickpeas',       'ml',     0.642),
  ('canned-black-beans',     'cup',    240),
  ('canned-black-beans',     'ml',     1.014),
  ('canned-cannellini-beans','cup',    262),
  ('canned-cannellini-beans','ml',     1.107),
  ('canned-kidney-beans',    'cup',    256),
  ('canned-kidney-beans',    'tbsp',   16),
  ('canned-kidney-beans',    'can',    436),
  ('canned-kidney-beans',    'ml',     1.082),
  ('brown-lentils',          'cup',    192),
  ('brown-lentils',          'tbsp',   12),
  ('brown-lentils',          'ml',     0.812),
  ('red-lentils',            'cup',    192),
  ('red-lentils',            'ml',     0.812),
  ('edamame',                'cup',    118),
  ('edamame',                'package',432),
  ('edamame',                'ml',     0.499),
  ('almonds',                'cup',    143),
  ('almonds',                'ml',     0.604),
  ('walnuts',                'cup',    117),
  ('walnuts',                'ml',     0.495),
  ('pecans',                 'cup',    109),
  ('pecans',                 'ml',     0.461),
  ('peanuts',                'cup',    146),
  ('peanuts',                'ml',     0.617),
  ('pine-nuts',              'cup',    135),
  ('pine-nuts',              'ml',     0.571),
  ('peanut-butter',          'tbsp',   16),
  ('peanut-butter',          'cup',    258),
  ('peanut-butter',          'ml',     1.091),
  ('tahini',                 'tbsp',   15),
  ('tahini',                 'ml',     1.014),
  ('extra-virgin-olive-oil', 'tbsp',   13.5),
  ('extra-virgin-olive-oil', 'cup',    216),
  ('extra-virgin-olive-oil', 'tsp',    4.5),
  ('extra-virgin-olive-oil', 'ml',     0.913),
  ('neutral-oil',            'tbsp',   14),
  ('neutral-oil',            'cup',    218),
  ('neutral-oil',            'tsp',    4.5),
  ('neutral-oil',            'ml',     0.921),
  ('sesame-oil',             'tbsp',   13.6),
  ('sesame-oil',             'cup',    218),
  ('sesame-oil',             'tsp',    4.5),
  ('sesame-oil',             'ml',     0.921),
  ('coconut-oil',            'tbsp',   13.6),
  ('coconut-oil',            'cup',    218),
  ('coconut-oil',            'tsp',    4.5),
  ('coconut-oil',            'ml',     0.921),
  ('coconut-milk',           'cup',    226),
  ('coconut-milk',           'tbsp',   15),
  ('coconut-milk',           'ml',     0.955),
  ('soy-sauce',              'tbsp',   16),
  ('soy-sauce',              'tsp',    5.3),
  ('soy-sauce',              'cup',    255),
  ('soy-sauce',              'ml',     1.078),
  ('fish-sauce',             'tbsp',   18),
  ('fish-sauce',             'ml',     1.217),
  ('oyster-sauce',           'tbsp',   18),
  ('oyster-sauce',           'ml',     1.217),
  ('hoisin-sauce',           'tbsp',   16),
  ('hoisin-sauce',           'ml',     1.082),
  ('red-wine-vinegar',       'tbsp',   14.9),
  ('red-wine-vinegar',       'cup',    239),
  ('red-wine-vinegar',       'tsp',    5),
  ('red-wine-vinegar',       'ml',     1.01),
  ('apple-cider-vinegar',    'tbsp',   14.9),
  ('apple-cider-vinegar',    'cup',    239),
  ('apple-cider-vinegar',    'tsp',    5),
  ('apple-cider-vinegar',    'ml',     1.01),
  ('balsamic-vinegar',       'tbsp',   16),
  ('balsamic-vinegar',       'cup',    255),
  ('balsamic-vinegar',       'tsp',    5.3),
  ('balsamic-vinegar',       'ml',     1.078),
  ('white-vinegar',          'tbsp',   14.9),
  ('white-vinegar',          'cup',    238),
  ('white-vinegar',          'tsp',    5),
  ('white-vinegar',          'ml',     1.006),
  ('mayonnaise',             'tbsp',   13.8),
  ('mayonnaise',             'cup',    220),
  ('mayonnaise',             'package',10),
  ('mayonnaise',             'ml',     0.93),
  ('ketchup',                'tbsp',   17),
  ('ketchup',                'package',9),
  ('ketchup',                'cup',    240),
  ('ketchup',                'ml',     1.014),
  ('worcestershire-sauce',   'tbsp',   17),
  ('worcestershire-sauce',   'cup',    275),
  ('worcestershire-sauce',   'ml',     1.162),
  ('sriracha',               'tsp',    6.5),
  ('sriracha',               'ml',     1.319),
  ('white-miso',             'tbsp',   17),
  ('white-miso',             'cup',    275),
  ('white-miso',             'ml',     1.162),
  ('tomato-paste',           'cup',    264),
  ('tomato-paste',           'tbsp',   16),
  ('tomato-paste',           'can',    170),
  ('tomato-paste',           'ml',     1.116),
  ('canned-crushed-tomatoes','cup',    242),
  ('canned-crushed-tomatoes','ml',     1.023),
  ('canned-whole-tomatoes',  'cup',    240),
  ('canned-whole-tomatoes',  'tbsp',   15),
  ('canned-whole-tomatoes',  'can',    190),
  ('canned-whole-tomatoes',  'each',   111),
  ('canned-whole-tomatoes',  'ml',     1.014),
  ('chicken-stock',          'cup',    240),
  ('chicken-stock',          'ml',     1.014),
  ('beef-stock',             'cup',    240),
  ('beef-stock',             'ml',     1.014),
  ('vegetable-stock',        'cup',    221),
  ('vegetable-stock',        'can',    390),
  ('vegetable-stock',        'ml',     0.934),
  ('capers',                 'tbsp',   8.6),
  ('capers',                 'ml',     0.582),
  ('dry-red-wine',           'fl_oz',  29.4),
  ('dry-red-wine',           'ml',     0.994),
  ('dry-white-wine',         'fl_oz',  29.4),
  ('dry-white-wine',         'ml',     0.994),
  ('lager',                  'fl_oz',  29.7),
  ('lager',                  'can',    356),
  ('lager',                  'ml',     1.004)
) AS c(slug, unit_code, grams)
JOIN ingredients i ON i.slug = c.slug;

INSERT INTO recipes (slug, title, description, servings, prep_min, cook_min, cuisine, methods) VALUES
  ('scallion-ginger-fried-rice', 'Scallion Ginger Fried Rice',
   'Weeknight fried rice built for day-old rice and whatever needs using up.',
   2, 10, 12, 'chinese', '{stir_fry}'),
  ('red-wine-braised-chuck', 'Red Wine Braised Chuck',
   'Low and slow chuck roast with onion and carrot.',
   4, 20, 180, 'french', '{sear,braise}');

INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, quantity, unit, preparation, raw_text, is_optional)
SELECT r.id, x.position, i.id, x.quantity, x.unit, x.preparation, x.raw_text, x.is_optional
FROM (VALUES
  ('scallion-ginger-fried-rice', 1, 'jasmine-rice', 2::numeric,   'cup',   'cooked, day-old',   '2 cups cooked jasmine rice, day-old', false),
  ('scallion-ginger-fried-rice', 2, 'scallion',     4,            'each',  'thinly sliced',     '4 scallions, thinly sliced',          false),
  ('scallion-ginger-fried-rice', 3, 'ginger',       15,           'g',     'minced',            '1 tbsp minced fresh ginger',          false),
  ('scallion-ginger-fried-rice', 4, 'garlic',       2,            'clove', 'minced',            '2 garlic cloves, minced',             false),
  ('scallion-ginger-fried-rice', 5, 'large-egg',    2,            'each',  'beaten',            '2 eggs, beaten',                      false),
  ('scallion-ginger-fried-rice', 6, 'soy-sauce',    2,            'tbsp',  NULL,                '2 tbsp soy sauce',                    false),
  ('red-wine-braised-chuck',     1, 'chuck-roast',  3,            'lb',    'cut into 3 pieces', '3 lb beef chuck, cut into 3 pieces',  false),
  ('red-wine-braised-chuck',     2, 'yellow-onion', 1,            'each',  'chopped',           '1 onion, chopped',                    false),
  ('red-wine-braised-chuck',     3, 'carrot',       2,            'each',  'chopped',           '2 carrots, chopped',                  false),
  ('red-wine-braised-chuck',     4, 'garlic',       4,            'clove', 'smashed',           '4 cloves garlic, smashed',            false),
  ('red-wine-braised-chuck',     5, 'kosher-salt',  NULL,         NULL,    NULL,                'salt to taste',                       false),
  ('red-wine-braised-chuck',     6, NULL,           1,            'cup',   NULL,                '1 cup dry red wine',                  false)  -- unresolved on purpose
) AS x(recipe_slug, position, ingredient_slug, quantity, unit, preparation, raw_text, is_optional)
JOIN recipes r ON r.slug = x.recipe_slug
LEFT JOIN ingredients i ON i.slug = x.ingredient_slug;

INSERT INTO recipe_steps (recipe_id, step_number, text)
SELECT r.id, s.step_number, s.text
FROM (VALUES
  ('scallion-ginger-fried-rice', 1, 'Scramble the eggs in a hot oiled wok and set aside.'),
  ('scallion-ginger-fried-rice', 2, 'Fry ginger, garlic, and scallion whites until fragrant.'),
  ('scallion-ginger-fried-rice', 3, 'Add rice, toss until hot and slightly crisp, then add soy sauce, eggs, and scallion greens.'),
  ('red-wine-braised-chuck',     1, 'Season and sear the chuck on all sides, then remove.'),
  ('red-wine-braised-chuck',     2, 'Soften onion, carrot, and garlic in the same pot.'),
  ('red-wine-braised-chuck',     3, 'Deglaze with wine, return the beef, cover, and braise at 300F for about 3 hours.')
) AS s(recipe_slug, step_number, text)
JOIN recipes r ON r.slug = s.recipe_slug;

INSERT INTO pantry_items (user_id, ingredient_id, quantity, unit, location, purchased_at, expires_at)
SELECT u.id, i.id, p.quantity, p.unit, p.location::pantry_location,
       current_date - p.bought_days_ago, current_date + p.expires_in_days
FROM (VALUES
  ('scallion',     6::numeric, 'each',  'fridge',  5, 2),
  ('garlic',       1,          'head',  'pantry', 10, 50),
  ('large-egg',    8,          'each',  'fridge', 12, 23),
  ('jasmine-rice', 4,          'cup',   'pantry', 30, 335),
  ('soy-sauce',    20,         'tbsp',  'pantry', 60, 670),
  ('chuck-roast',  3,          'lb',    'freezer', 3, 90)
) AS p(slug, quantity, unit, location, bought_days_ago, expires_in_days)
JOIN ingredients i ON i.slug = p.slug
CROSS JOIN users u
WHERE u.email = 'dev@stockpot.local';

COMMIT;
